### ISSUE TITLE
I'm trying to remove cell border but I'm unable to handle it

### ISSUE THREAD

**Issue by sajidfrommerqata** [mui-org/material-ui-x#1442]
I tried disableClickEventBubbling and disableSelectionOnClick but both are showing no effect for the cell border.

For more details, please look at the screenshot.

Screenshot: https://prnt.sc/11qkp1s

Sandbox: https://codesandbox.io/s/datagrid-quick-start-forked-7s4rs

Thanks

**Comment by dtassone** [comment]
You can do it with css
![image](https://user-images.githubusercontent.com/936978/115377360-d643c580-a1cf-11eb-89a7-8a73617bb241.png)

**Comment by oliviertassinari** [comment]
@dtassone Please provide a code version, so @sajidfrommerqata can copy and paste it.

**Comment by dtassone** [comment]
```css
.MuiDataGrid-root .MuiDataGrid-cell:focus-within {
    outline: solid #3f51b5 1px;
    outline-offset: -1px;
}
```

**Comment by sajidfrommerqata** [comment]
Thank you @dtassone and @oliviertassinari

**Comment by zzossig** [comment]
Don't forget to add `!important`
```css
.MuiDataGrid-root .MuiDataGrid-cell:focus-within {
    outline: solid #3f51b5 1px !important;
    outline-offset: -1px;
}
```
